from .libs import *

INPUT_LIST = {
    K_0: 'à',
    K_1: '&',
    K_2: 'é',
    K_3: '"',
    K_4: '\'',
    K_5: '(',
    K_6: '-',
    K_7: 'è',
    K_8: '_',
    K_9: 'ç',
    K_SPACE: ' ',
    K_LEFT: "LEFT",
    K_RIGHT: "RIGHT",
    K_UP: "UP",
    K_DOWN: "DOWN",
    K_DELETE: "RDEL",
    K_RETURN: "\n",
    K_DOLLAR: '$',
    K_ASTERISK: '*',
    K_EQUALS: '=',
    K_COMMA: ',',
    K_SEMICOLON: ';',
    K_EXCLAIM: '!',
    K_LESS: '<',
    K_RIGHTPAREN: ')',
    K_COLON: ':',
    K_CARET: '^',
    K_a: 'a',
    K_b: 'b',
    K_c: 'c',
    K_d: 'd',
    K_e: 'e',
    K_f: 'f',
    K_g: 'g',
    K_h: 'h',
    K_i: 'i',
    K_j: 'j',
    K_k: 'k',
    K_l: 'l',
    K_m: 'm',
    K_n: 'n',
    K_o: 'o',
    K_p: 'p',
    K_q: 'q',
    K_r: 'r',
    K_s: 's',
    K_t: 't',
    K_u: 'u',
    K_v: 'v',
    K_w: 'w',
    K_x: 'x',
    K_y: 'y',
    K_z: 'z',
    K_KP_0: '0',
    K_KP_1: '1',
    K_KP_2: '2',
    K_KP_3: '3',
    K_KP_4: '4',
    K_KP_5: '5',
    K_KP_6: '6',
    K_KP_7: '7',
    K_KP_8: '8',
    K_KP_9: '9',
    K_KP_DIVIDE: '/',
    K_KP_ENTER: '\n',
    K_KP_MULTIPLY: '*',
    K_KP_MINUS: '-',
    K_KP_PLUS: '+',
    K_KP_PERIOD: '.',
    8: "LDEL"
}

ALT_INPUT_LIST = {
    K_0: '@',
    K_1: '&',
    K_2: '~',
    K_3: '#',
    K_4: '{',
    K_5: '[',
    K_6: '|',
    K_7: '`',
    K_8: '\\',
    K_9: '^',
    K_SPACE: ' ',
    K_LEFT: "LEFT",
    K_RIGHT: "RIGHT",
    K_UP: "UP",
    K_DOWN: "DOWN",
    K_DELETE: "RDEL",
    K_RETURN: "\n",
    K_DOLLAR: '¤',
    K_ASTERISK: '*',
    K_EQUALS: '}',
    K_COMMA: ',',
    K_SEMICOLON: ';',
    K_EXCLAIM: '!',
    K_LESS: '<',
    K_RIGHTPAREN: ']',
    K_COLON: ':',
    K_CARET: '^',
    K_a: 'a',
    K_b: 'b',
    K_c: 'c',
    K_d: 'd',
    K_e: '€',
    K_f: 'f',
    K_g: 'g',
    K_h: 'h',
    K_i: 'i',
    K_j: 'j',
    K_k: 'k',
    K_l: 'l',
    K_m: 'm',
    K_n: 'n',
    K_o: 'o',
    K_p: 'p',
    K_q: 'q',
    K_r: 'r',
    K_s: 's',
    K_t: 't',
    K_u: 'u',
    K_v: 'v',
    K_w: 'w',
    K_x: 'x',
    K_y: 'y',
    K_z: 'z',
    K_KP_0: '0',
    K_KP_1: '1',
    K_KP_2: '2',
    K_KP_3: '3',
    K_KP_4: '4',
    K_KP_5: '5',
    K_KP_6: '6',
    K_KP_7: '7',
    K_KP_8: '8',
    K_KP_9: '9',
    K_KP_DIVIDE: '/',
    K_KP_ENTER: '\n',
    K_KP_MULTIPLY: '*',
    K_KP_MINUS: '-',
    K_KP_PLUS: '+',
    K_KP_PERIOD: '.',
    8: "LDEL"
}

MAJ_INPUT_LIST = {
    K_0: '0',
    K_1: '1',
    K_2: '2',
    K_3: '3',
    K_4: '4',
    K_5: '5',
    K_6: '6',
    K_7: '7',
    K_8: '8',
    K_9: '9',
    K_SPACE: ' ',
    K_LEFT: "LEFT",
    K_RIGHT: "RIGHT",
    K_UP: "UP",
    K_DOWN: "DOWN",
    K_DELETE: "RDEL",
    K_RETURN: "\n",
    K_DOLLAR: '£',
    K_ASTERISK: 'µ',
    K_EQUALS: '+',
    K_COMMA: '?',
    K_SEMICOLON: '.',
    K_EXCLAIM: '§',
    K_LESS: '>',
    K_RIGHTPAREN: '°',
    K_COLON: '/',
    K_CARET: '¨',
    K_a: 'A',
    K_b: 'B',
    K_c: 'C',
    K_d: 'D',
    K_e: 'E',
    K_f: 'F',
    K_g: 'G',
    K_h: 'H',
    K_i: 'I',
    K_j: 'J',
    K_k: 'K',
    K_l: 'L',
    K_m: 'M',
    K_n: 'N',
    K_o: 'O',
    K_p: 'P',
    K_q: 'Q',
    K_r: 'R',
    K_s: 'S',
    K_t: 'T',
    K_u: 'U',
    K_v: 'V',
    K_w: 'W',
    K_x: 'X',
    K_y: 'Y',
    K_z: 'Z',
    K_KP_0: '0',
    K_KP_1: '1',
    K_KP_2: '2',
    K_KP_3: '3',
    K_KP_4: '4',
    K_KP_5: '5',
    K_KP_6: '6',
    K_KP_7: '7',
    K_KP_8: '8',
    K_KP_9: '9',
    K_KP_DIVIDE: '/',
    K_KP_ENTER: '\n',
    K_KP_MULTIPLY: '*',
    K_KP_MINUS: '-',
    K_KP_PLUS: '+',
    K_KP_PERIOD: '.',
    8: "LDEL"
}

TAG_GLD_LANG: dict = {
    "objects"
}

FPS: int = 60

Z_SORT_RULE = lambda item: item.z

PLAYER_MOVE_RIGHT = lambda p: p.move(p.x + p.force, p.y, p.z)
PLAYER_MOVE_LEFT = lambda p: p.move(p.x - p.force, p.y, p.z)
PLAYER_MOVE_UP = lambda p: p.move(p.x, p.y - p.force, p.z)
PLAYER_MOVE_DOWN = lambda p: p.move(p.x, p.y + p.force, p.z)
TRUE_CONDITION = lambda p, k: True

DATAS_PATH = "./datas"

IMAGES_PATH = "$data$/images".replace("$data$", DATAS_PATH)

SHEETS_PATH = "$images_path$/sheets".replace("$images_path$", IMAGES_PATH)

IMAGES_INCLUDE = "$images_path$/include.cnd".replace("$images_path$", IMAGES_PATH)

if isfile(IMAGES_INCLUDE):
    INCLUDES = {"image": DataBase(IMAGES_INCLUDE)}

LOADED_IMAGES = {}

ASSOCIATION = {
    "$data$": DATAS_PATH,
    "$images_path$": IMAGES_PATH,
    "$sheets_path$": SHEETS_PATH
}